dbt_learning_project:
  target: "{{ env_var('DBT_DEFAULT_TARGET', 'dev') }}"
  outputs:
    dev:
      dataset: "{{ env_var('DEV_DATASET') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('DEV_KEYFILE') }}"
      location: US
      method: service-account
      priority: interactive
      project: dbt-learning-423822
      threads: 16
      type: bigquery
  target: dev